<a href="https://colab.research.google.com/github/tyagosousa/Introdu-o-ao-NumPy/blob/main/No%C3%A7%C3%B5es_de_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Criação de array


In [54]:
import numpy as np

In [55]:
array1 = np.array([2, 8, 7, 1, 0, 9])

In [56]:
array1

array([2, 8, 7, 1, 0, 9])

In [57]:
type(array1)

numpy.ndarray

In [58]:
array1[1:4]

array([8, 7, 1])

In [59]:
indices = [2, 5, 1]
array1[indices]

array([7, 9, 8])

In [60]:
mascara = (array1 % 2 != 0)
mascara

array([False, False,  True,  True, False,  True])

In [61]:
array1[mascara]

array([7, 1, 9])

In [62]:
array1[0] = 10
array1

array([10,  8,  7,  1,  0,  9])

#Métodos

In [63]:
array2 = np.array([8, 10, 7, 5, 6, 8, 2, 1, 0])

In [64]:
array2.shape

(9,)

In [65]:
array2.cumsum()

array([ 8, 18, 25, 30, 36, 44, 46, 47, 47])

In [66]:
array2.cumprod()

array([     8,     80,    560,   2800,  16800, 134400, 268800, 268800,
            0])

In [67]:
array3 = np.arange(0, 20, 3)
array3

array([ 0,  3,  6,  9, 12, 15, 18])

In [68]:
array4 = np.zeros(5)
array4

array([0., 0., 0., 0., 0.])

In [69]:
array5 = np.eye(5)
array5

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [70]:
array6 = np.diag(np.array([1, 2, 3, 4, 5]))
array6

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [71]:
print(np.linspace(0, 10))

[ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ]


In [72]:
print(np.linspace(0, 20, 7))

[ 0.          3.33333333  6.66666667 10.         13.33333333 16.66666667
 20.        ]


In [73]:
print(np.logspace(0, 10, 4))

[1.00000000e+00 2.15443469e+03 4.64158883e+06 1.00000000e+10]


In [74]:
print(np.ones(5, dtype=float))

[1. 1. 1. 1. 1.]


In [75]:
print(np.zeros_like(array2))

[0 0 0 0 0 0 0 0 0]


In [76]:
print(np.ones_like(array2))

[1 1 1 1 1 1 1 1 1]


In [77]:
print(np.zeros((5, 8)))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]
